/**
 * Conventional Changelog 解析器選項配置
 * Conventional Changelog Parser Options Configuration
 *
 * 此模組定義 commit 訊息的解析規則，包括標準格式與 emoji 格式的支援、BREAKING CHANGE 偵測、revert 識別等。
 * This module defines parsing rules for commit messages, including support for standard and emoji formats, BREAKING CHANGE detection, revert identification, etc.
 *
 * @module parser-opts
 */
'use strict'

const emojiRegex = require('emoji-regex')();

/**
 * 標準 commit 標題格式正則表達式
 * Standard commit header format regex
 *
 * 匹配格式：type(scope)!: subject
 * Matches format: type(scope)!: subject
 * - type: commit 類型（必需）/ commit type (required)
 * - scope: 影響範圍（可選）/ scope of impact (optional)
 * - !: BREAKING CHANGE 標記（可選）/ BREAKING CHANGE marker (optional)
 * - subject: 簡短描述（必需）/ brief description (required)
 *
 * 範例 / Examples: "feat: add feature", "fix(api): bug fix", "feat!: breaking change"
 */
const headerPattern = /^(\w+)(?:\(([^)]*)\))?!?:\s+(.*)$/;
/**
 * BREAKING CHANGE 標題格式正則表達式
 * BREAKING CHANGE header format regex
 *
 * 與 headerPattern 類似，但要求必須包含 "!" 標記以明確標示 BREAKING CHANGE。
 * Similar to headerPattern, but requires the "!" marker to explicitly indicate a BREAKING CHANGE.
 *
 * 範例 / Example: "feat(api)!: breaking change"
 */
const breakingHeaderPattern = /^(\w+)(?:\(([^)]*)\))?!:\s+(.*)$/;

/**
 * 增強型標題格式正則表達式（支援 emoji）
 * Enhanced header format regex (with emoji support)
 *
 * 此正則表達式同時支援兩種格式：
 * This regex supports two formats simultaneously:
 * 1. 標準格式：type(scope)!: subject / Standard format: type(scope)!: subject
 * 2. Emoji 格式：emoji(scope) subject / Emoji format: emoji(scope) subject
 *
 * 使用 'u' 旗標以正確處理 Unicode emoji 字元。
 * Uses 'u' flag to correctly handle Unicode emoji characters.
 */
const re2 = new RegExp(`^(?:(\\w+)(?:\\(([^)]*)\\))?!?:|(${emojiRegex.source})(?:\\((.+)\\))?)\\s+(.*)$`, 'u')

/**
 * 自定義 headerPattern 的匹配方法
 * Custom matching method for headerPattern
 *
 * 覆寫原生的 Symbol.match 和 exec 方法，使用增強型正則表達式 re2 進行匹配。
 * Overrides native Symbol.match and exec methods to use the enhanced regex re2 for matching.
 *
 * 此方法處理兩種格式的匹配結果，並將其標準化為統一的陣列格式：
 * This method processes matching results from both formats and normalizes them to a unified array format:
 * [fullMatch, type, scope, subject]
 *
 * 對於 emoji 格式，會將 emoji 視為 type，並重新排列捕獲群組。
 * For emoji format, treats the emoji as the type and rearranges capture groups.
 */
headerPattern[Symbol.match] = headerPattern.exec = function (str)
{
  // 使用增強型正則表達式進行匹配
  // Use enhanced regex for matching
  let result = re2.exec(str);

  if (result)
  {
    // 檢測是否為 emoji 格式（group 1 和 2 未定義，但 group 3 有值）
    // Detect if it's emoji format (groups 1 and 2 undefined, but group 3 has value)
    if (typeof result[1] === 'undefined' && typeof result[2] === 'undefined' && typeof result[3] !== 'undefined')
    {
      // 將 emoji（group 3）移到 type 位置（group 1）
      // Move emoji (group 3) to type position (group 1)
      result[1] = result[3]
      // 將 emoji 的 scope（group 4）移到標準 scope 位置（group 2）
      // Move emoji's scope (group 4) to standard scope position (group 2)
      result[2] = result[4]
    }

    // 移除多餘的捕獲群組（group 3 和 4）
    // Remove redundant capture groups (groups 3 and 4)
    result.splice(3, 2)
  }

  return result
}

/**
 * 解析器選項配置物件
 * Parser Options Configuration Object
 *
 * 定義如何解析 conventional commit 訊息的各個部分。
 * Defines how to parse various parts of conventional commit messages.
 *
 * @type { import('conventional-changelog-core').ParserOptions }
 */
const parserOpts = {
  // 使用自定義的標題匹配模式（支援 emoji）
  // Use custom header matching pattern (with emoji support)
  headerPattern,
  /**
   * 標題捕獲群組對應關係
   * Header capture group correspondence
   *
   * 定義正則表達式捕獲群組與 commit 屬性的對應關係。
   * Defines the mapping between regex capture groups and commit properties.
   * [1] -> type, [2] -> scope, [3] -> subject
   */
  headerCorrespondence: [
    'type',
    'scope',
    'subject'
  ],

  // BREAKING CHANGE 專用的標題匹配模式（要求 "!" 標記）
  // Dedicated header pattern for BREAKING CHANGE (requires "!" marker)
  breakingHeaderPattern,

  /**
   * 註記關鍵字列表
   * Note keywords list
   *
   * 定義在 commit body 或 footer 中會被識別為特殊註記的關鍵字。
   * Defines keywords in commit body or footer that will be recognized as special notes.
   *
   * 這些關鍵字會觸發特殊處理，如 BREAKING CHANGE 會影響版本升級決策。
   * These keywords trigger special handling, e.g., BREAKING CHANGE affects version bump decisions.
   */
  noteKeywords: [
    'BREAKING-CHANGE',
    'BREAKING CHANGE',
    'TODO',
    'FIXME'
  ],
  /**
   * Revert commit 匹配模式
   * Revert commit matching pattern
   *
   * 識別 revert commit 的格式，通常由 git revert 自動生成。
   * Identifies revert commit format, typically auto-generated by git revert.
   *
   * 範例 / Example: "Revert \"feat: add feature\" This reverts commit abc123."
   */
  revertPattern: /^(?:Revert|revert:)\s"?([\s\S]+?)"?\s*This reverts commit (\w*)\./i,
  /**
   * Revert 捕獲群組對應關係
   * Revert capture group correspondence
   *
   * [1] -> header (被 revert 的 commit 標題), [2] -> hash (被 revert 的 commit hash)
   * [1] -> header (reverted commit header), [2] -> hash (reverted commit hash)
   */
  revertCorrespondence: ['header', 'hash'],

  /**
   * 引用動作關鍵字列表
   * Reference action keywords list
   *
   * 定義在 commit 訊息中用於引用 issue/PR 的動作關鍵字。
   * Defines action keywords used to reference issues/PRs in commit messages.
   *
   * 這些關鍵字會被解析為與 issue/PR 的關聯，某些關鍵字（如 close, fix）可能觸發自動關閉 issue。
   * These keywords are parsed as associations with issues/PRs; some keywords (like close, fix) may trigger automatic issue closure.
   *
   * 範例 / Examples: "fixes #123", "closes #456", "see #789"
   */
  referenceActions: [
    'close',
    'closes',
    'closed',
    'fix',
    'fixes',
    'fixed',
    'resolve',
    'resolves',
    'resolved',
    'issues',
    'pr',
    'see',
  ],
}

module.exports = parserOpts
