"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emoji = void 0;
var emoji;
(function (emoji) {
    emoji["docs"] = "\uD83D\uDCDA";
    emoji["feature"] = "\u2728";
    emoji["fix"] = "\uD83D\uDC1B";
    emoji["improvement"] = "\uD83C\uDF08";
    emoji["removal"] = "\uD83D\uDCA9";
    emoji["style"] = "\uD83D\uDC8E";
    emoji["tag"] = "\uD83D\uDD16";
    emoji["test"] = "\uD83D\uDEA8";
    emoji["tooling"] = "\uD83D\uDEE0";
    emoji["feat"] = "\u2728";
    emoji["initial"] = "\uD83C\uDF89";
    emoji["dependencies"] = "\u2B06\uFE0F";
    emoji["peerDependencies"] = "\u2B06\uFE0F";
    emoji["metadata"] = "\uD83D\uDCE6";
    emoji["refactor"] = "\uD83D\uDCE6";
    emoji["perf"] = "\uD83D\uDE80";
    emoji["build"] = "\uD83D\uDEE0";
    emoji["ci"] = "\u2699\uFE0F";
    emoji["chore"] = "\u267B\uFE0F";
    emoji["devDependencies"] = "\u2B06\uFE0F";
    emoji["revert"] = "\uD83D\uDDD1";
})(emoji = exports.emoji || (exports.emoji = {}));
;
exports.default = emoji;
//# sourceMappingURL=emoji.js.map